# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.4
    hooks:
      - id: clang-format
  - repo: local
    hooks:
      - id: cppcheck
        name: cppcheck
        entry: cppcheck
        language: system
        args:
          [
           --enable=all,
           --suppress=unusedFunction,
           --suppress=unmatchedSuppression,
           --suppress=missingIncludeSystem,
           --suppress=toomanyconfigs,
           --error-exitcode=1,
          ]
        files: \.(c|h|cpp)$
